name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'
        
    - name: Build Docker image
      run: |
        docker build -t ramibhs/intership:${{ github.sha }} .
        echo "DOCKER_IMAGE=ramibhs/intership:${{ github.sha }}" >> $GITHUB_ENV

    - name: Log in to Docker Hub
      run: echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

    - name: Push Docker image to Docker Hub
      run: docker push ramibhs/intership:${{ github.sha }}
      
    - name: Display deploy.yaml before modification
      run: cat k8s/deployment.yaml
      
    - name: Update image tag in deployment.yaml
      uses: OpsVerseIO/image-updater-action@0.1.0
      with:
        valueFile: 'k8s/deployment.yaml'
        propertyPath: 'spec.template.spec.containers[0].image'
        value: ramibhs/jenkins:${{ github.sha }}
        commitChange: false
        branch: master
        targetBranch: master
        createPR: false
        message: 'Update deployment image to ramibhs/jenkins:${{ github.sha }}'
        token: ${{ secrets.TOKEN }}
        
    - name: Display deploy.yaml after modification
      run: cat k8s/deployment.yaml

    - name: Apply Kubernetes deployment
      env:
        KUBECONFIG: ${{ secrets.KUBE_CONFIG_DATA }}
      run: |
        echo "${KUBECONFIG}" | base64 --decode > $HOME/.kube/config
        kubectl apply -f k8s/deployment.yaml -n myapp
        
    - name: Notify Slack on success
      if: success()
      uses: 8398a7/action-slack@v3
      with:
        status: success
        fields: repo,commit,author,commit_message,action,eventName,ref,workflow,job,took
        author_name: GitHub Actions
        github_token: ${{ secrets.TOKEN }}  # Required for accessing GitHub API
        channel: '#general'  # Replace with your Slack channel name
        slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}  # This is how you should reference your secret
      env:
        CI: true

    - name: Notify Slack on failure
      if: failure()
      uses: 8398a7/action-slack@v3
      with:
        status: failure
        fields: repo,commit,author,commit_message,action,eventName,ref,workflow,job,took
        author_name: GitHub Actions
        github_token: ${{ secrets.TOKEN }}  # Required for accessing GitHub API
        channel: '#general'  # Replace with your Slack channel name
        slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}  # Ensure correct referencing
      env:
        CI: true
