name: Test and Merge

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Test
      run: dotnet test --configuration Release --no-build

  merge:
    name: Merge if tests pass
    needs: test
    runs-on: ubuntu-latest
    if: ${{ needs.test.result == 'success' }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Merge to main
      run: |
        git config --global user.email "ramibelhadjsalem@gmail.com"
        git config --global user.name "ramibelhadjsalem"
        git fetch --all
        git checkout master
        git merge ${{ github.event.after }}
        git push
